import { FormType, FormTiming, IFormMetadataView } from '../forms';

export const MOCK_FORMS: IFormMetadataView[] = [
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Bus Waiver',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
  },
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Waiver',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
    description: 'Hello there!',
  },
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Super very huge Longer Form Title',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
  },
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Waiver',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
  },
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Waiver',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
  },
  {
    formId: 'hello',
    formType: FormType.enum.WAIVER,
    published: new Date(),
    publisher: 'Ben Glossner',
    title: 'Waiver',
    viewable: false,
    startDate: new Date(),
    endDate: new Date((new Date().getTime() + 10000)),
    timing: FormTiming.ACTIVE,
  },
];
